name: cashier_app
description: نظام كاشير متكامل - Windows
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  intl: ^0.18.1
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.3
  fl_chart: ^0.65.0
  data_table_2: ^2.5.12
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  excel: ^4.0.2
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
