name: Build Windows
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Create Flutter project
        run: flutter create --platforms=windows --project-name cashair_system . 

      - name: Create asset folders
        run: |
          mkdir -Force assets/fonts
          mkdir -Force assets/images

      - name: Download Cairo Font
        run: |
          curl -L "https://fonts.gstatic.com/s/cairo/v28/SLXgc1nY6HkvangtZmpQdkhzfH5lkSs2SgRjCAGMQ1z0hOA-W1ToLQ-HmkT0.ttf" -o assets/fonts/Cairo-Regular.ttf
          curl -L "https://fonts.gstatic.com/s/cairo/v28/SLXgc1nY6HkvangtZmpQdkhzfH5lkSs2SgRjCAGMQ1z0hD4-W1ToLQ-HmkT0.ttf" -o assets/fonts/Cairo-Bold.ttf

      - run: flutter pub get

      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: cashier-app-windows
          path: build/windows/x64/runner/Release/
